
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed-ucs
      - mongo-seed-users
  mongo-seed-ucs:
    image: mongo:latest
    volumes:
      - /home/user/Desktop/3ºAno/EW/Trabalho-EW-2024/datasets/ucs.json:/datasets/ucs.json
    command: mongoimport --host mongodb -d UCS -c ucs --type json --file /datasets/ucs.json --jsonArray
  mongo-seed-users:
    image: mongo:latest
    volumes:
      - /home/user/Desktop/3ºAno/EW/Trabalho-EW-2024/datasets/users.json:/datasets/users.json
    command: mongoimport --host mongodb -d UCS -c users --type json --file /datasets/users.json --jsonArray
